cluster.name: "docker-cluster"
node.name: es03
bootstrap.memory_lock: true
xpack.security.enabled: false
network.host: 0.0.0.0
discovery.seed_hosts: ["es01","es02","es03"]
cluster.initial_master_nodes: ["es01","es02","es03"]
